[build]
  command = "npm run build:netlify"
  functions = "netlify/functions"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[functions]
  node_bundler = "esbuild"

# Handle Next.js routing - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 